### ISSUE TITLE
Present gallery mode images in a grid

### ISSUE THREAD

**Issue by bakape** [bakape/meguca#657]
Only thing to keep are the image search and download links. Can be done purely in CSS. 
Prototype CSS: 
```css
.post-container {
  display: flex;
  min-width: initial;
}
article {
  padding: 0.5em;
}
article figure {
  margin: 0;
}
article:not(.media),
figcaption > *:not(.image-search-container),
blockquote,
.backlinks,
header {
  display: none;
}
#thread-container {
  display: inline-table;
}
```
