### ISSUE TITLE
Update glass theme

### ISSUE THREAD

**Issue by bakape** [bakape/meguca#903]
Merge this into it. Will also need to update background.ts composite overlay colours. 
```css
article{color:#dddddd; min-width:340px; max-width:48.5%;}
article,aside{margin:3px}
figure{margin-right:0}
#threads{margin-left:-.4%}
#mascot-image {right:1.5%; max-height:95%; max-width:43%;}
#banner {background:#333333;border-bottom:#222222; height:auto;}
#threads hr {display:none;}
.glass {background:linear-gradient(rgba(30,30,30,0.5), rgba(30,30,30,0.5));}
#lock{margin-left:0; padding-left:2px;}
aside.posting{ margin:1px 0 0 1px;}
.aside-container{margin: 13px 0 0 1px}
#hover-overlay>img, #hover-overlay>video {padding-bottom:22px;} 
```
